# Use root/example as user/password credentials
version: "3.1"
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
  backend:
    build:
      context: ../API
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - URL_FRONTEND=http://localhost
    ports:
      - 3000:3000
  nginx:
    image: nginx:1.25.4
    volumes:
      - ../instagram-ui/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"